version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "%(asctime)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: src/logs/app.log
    maxBytes: 10_000_000
    backupCount: 5
    encoding: utf-8

loggers:
  extract:
    level: INFO
    handlers: [console, file]
    propagate: False
  
  transform:
    level: INFO
    handlers: [console, file]
    propagate: False